const supabase = require('./_db');

const PROJECTS = [
  {project:"Risk EOD — Exchange File Downloads",category:"Automation",status:"Live",priority:"P1",rag:"G",owner:"Risk team",spoc:"Mahek",tech:"Python",blocker:"",eta:"",mc:"No",mc_reason:"Fully automated scheduled download; no human decision point in the pipeline.",current_status:"Daily exchange file download via RPA. BSE(2), MTM, NSE(8), Surveillance(1) all running."},
  {project:"File Download Swap Fix",category:"Automation",status:"Live",priority:"P1",rag:"G",owner:"Risk team",spoc:"Mahek",tech:"Python",blocker:"",eta:"",mc:"No",mc_reason:"Technical bug-fix automation; no financial transaction or approval gate.",current_status:"File download swap fix deployed."},
  {project:"Matrix EOD — Exchange File Downloads",category:"Automation",status:"On Hold",priority:"P2",rag:"G",owner:"Swapnil Mohile",spoc:"Mahek",tech:"Python",blocker:"",eta:"2026-06-15",mc:"No",mc_reason:"Automated download pipeline; human involvement only for UAT sign-off.",current_status:"NSE(6), NSE Direct(1), BSE(8), Commodity(1). Dev and API done. Firewall request for Commodity pending."},
  {project:"Power Automate Server Migration (86-206)",category:"Infrastructure",status:"Live",priority:"P2",rag:"G",owner:"Team",spoc:"",tech:"Power Automate",blocker:"",eta:"",mc:"Partial",mc_reason:"Ongoing maker-checker needed if flows are added/modified.",current_status:"Week 3 complete. PA v2.68 installed and tested. Load balancer running."},
  {project:"LD Dematrix — Reco & Migration",category:"Data Reconciliation/Migration",status:"Blocked",priority:"P2",rag:"G",owner:"Jaydeep Deshmukh",spoc:"Arnav Singh / Manasi Kambli",tech:"SQL",blocker:"",eta:"",mc:"Yes",mc_reason:"Data migration to production requires SPD sign-off.",current_status:"Reco completed. Migration done. Waiting for SPD team feedback."},
  {project:"Databricks Platform Setup",category:"Infrastructure",status:"Blocked",priority:"P1",rag:"R",owner:"Yogesh Kanani",spoc:"Yogesh Kanani",tech:"Databricks, AWS",blocker:"Infra issue - blank screen on access",eta:"",mc:"Partial",mc_reason:"Access setup requires IT/infra approval at each step (PAM, SR).",current_status:"SR approved. PAM access OK. Blank screen at infra end blocks access."},
  {project:"Streaming Market Data API",category:"Development",status:"Waiting",priority:"P3",rag:"A",owner:"Govind Birajdar",spoc:"Naincy Raj",tech:"Python",blocker:"",eta:"",mc:"Partial",mc_reason:"SSL/firewall changes require infra approval; API whitelisting is a manual gate.",current_status:"Insomnia approved, installation pending. SSL error unresolved."},
  {project:"AWS — Knowledge Graph",category:"Development",status:"In Progress",priority:"P1",rag:"A",owner:"CS Team",spoc:"Naincy Raj",tech:"AWS, Python",blocker:"",eta:"",mc:"Yes",mc_reason:"AI/ML output needs business validation before consumption.",current_status:"AWS setup and discussions with AWS team on infra."},
  {project:"Email Repository — Source Ingestion",category:"Development",status:"In Progress",priority:"P2",rag:"G",owner:"Bhupendra Singh",spoc:"Naincy Raj",tech:"Python, SSIS, API",blocker:"ComTrack data not received",eta:"",mc:"Partial",mc_reason:"Master table structure requires business review.",current_status:"Zentech: live. CRM: done. Esigner: sample done. LD: sample done. Netcore: received. Dematrix: pending."},
  {project:"PROD/UAT Environment Standardization",category:"Standardization",status:"Live",priority:"P2",rag:"G",owner:"Team",spoc:"",tech:"Power Automate",blocker:"",eta:"",mc:"No",mc_reason:"Internal folder structure standardization; no external approvals needed.",current_status:"PROD and UAT folder structure defined. Exchange file download done."},
  {project:"Email/Teams Notification Standardization",category:"Standardization",status:"Live",priority:"P2",rag:"G",owner:"Team",spoc:"",tech:"Power Automate, Teams",blocker:"",eta:"",mc:"No",mc_reason:"Notification templates are internal; changes can be deployed without approval gates.",current_status:"Exchange file download Email and Teams done. BOD, TPP, Matrix pending."},
  {project:"Server Setup — 10.6.103.177",category:"Infrastructure",status:"In Progress",priority:"P3",rag:"A",owner:"Internal Team",spoc:"",tech:"",blocker:"",eta:"",mc:"Partial",mc_reason:"Server provisioning requires IT change-management approval.",current_status:"Server 10.6.103.177 setup in progress."},
  {project:"Server Setup — 10.6.123.181",category:"Infrastructure",status:"In Progress",priority:"P3",rag:"A",owner:"Internal Team",spoc:"",tech:"",blocker:"",eta:"",mc:"Partial",mc_reason:"Server provisioning requires IT change-management approval.",current_status:"Server 10.6.123.181 setup in progress."},
  {project:"Git & Azure DevOps Setup",category:"Infrastructure",status:"In Progress",priority:"P3",rag:"G",owner:"Prashant Patil",spoc:"",tech:"Git, Azure DevOps",blocker:"",eta:"",mc:"Partial",mc_reason:"Installation approval pending from Nachiket; access policy requires manager sign-off.",current_status:"GIT LIB created. Nachiket approval done. Installation approval pending."},
  {project:"CIBIL API — Fetch & Return Credit Details",category:"Development",status:"In Progress",priority:"P2",rag:"R",owner:"Rohan Balgude",spoc:"",tech:"API, Python",blocker:"",eta:"",mc:"Yes",mc_reason:"Credit data is highly sensitive; any data fetch/return must have audit trail.",current_status:"UAT: 3 files shared. PROD IP whitelisting pending from Experian."},
  {project:"Ubona — Audio Recording Storage & Fetching",category:"Automation",status:"In Progress",priority:"P2",rag:"R",owner:"Jimmy Joshi",spoc:"",tech:"AWS, Python",blocker:"Waiting for UBONA response on S3 transfer",eta:"",mc:"Yes",mc_reason:"Audio recordings are sensitive PII; must be reviewed by compliance.",current_status:"Maintain Ubona audio files with transcription and AI-based analysis."},
  {project:"Ubona — Salesforce Integration",category:"Development",status:"Blocked",priority:"P1",rag:"R",owner:"Jimmy Joshi",spoc:"",tech:"AWS Lambda, API",blocker:"Ubona side file transfer pending",eta:"2026-06-30",mc:"Yes",mc_reason:"Salesforce integration involves client data flow; requires security and business approval.",current_status:"API Readiness done. DNS done. Lambda auth with Aamir pending."},
  {project:"TPP — AMC Automation",category:"Automation",status:"Blocked",priority:"P2",rag:"R",owner:"BSG",spoc:"",tech:"Playwright, Python",blocker:"Email 44 AMCs mapper not received from BSG.",eta:"",mc:"Yes",mc_reason:"AMC portal submission involves financial transactions; OTP login is a maker-checker mechanism.",current_status:"40 files, 12 AMCs done. 1 AMC OTP issue. Mapper for 44 AMCs awaited from BSG."},
  {project:"Hawkeye — Risk Exec Automation",category:"Standardization",status:"Requirement Gathering",priority:"P2",rag:"R",owner:"Team",spoc:"",tech:"Power Automate",blocker:"Waiting for access to 146 server",eta:"",mc:"Yes",mc_reason:"Risk exec outputs are regulatory-facing; must be validated by Risk team.",current_status:"Process understanding done. ADC and EDC 3 exes each. No UAT on vendor side."},
  {project:"NRI PIN Balance — Email Automation",category:"Automation",status:"Live",priority:"P3",rag:"G",owner:"OPS Team",spoc:"",tech:"Power Automate, SQL",blocker:"",eta:"",mc:"No",mc_reason:"Fully automated notification; no financial action taken.",current_status:"LIVE. Email download, SP execution, all notifications working."},
  {project:"BOD — Exchange File Downloads",category:"Automation",status:"Live",priority:"P2",rag:"G",owner:"Kiran Amin",spoc:"",tech:"API, Python",blocker:"",eta:"",mc:"No",mc_reason:"Automated file download at BOD; no manual decision point.",current_status:"LIVE. API, NMass(9), NSE Member Portal(2), NSE Index NCDX(2), NSE Normal(2) all running."},
  {project:"SBOS Settlement Reco (18 items)",category:"Data Reconciliation/Migration",status:"In Progress",priority:"P2",rag:"A",owner:"Jayesh Mistri",spoc:"",tech:"Python, SQL",blocker:"mapping awaited",eta:"",mc:"Yes",mc_reason:"Settlement reconciliation has direct financial implications; exceptions must be reviewed.",current_status:"File download via Excel macro understood. Waiting for final BRD and mapping."},
  {project:"PROP & ALLOCATION Risk Macro Automation",category:"Automation",status:"In Progress",priority:"P1",rag:"A",owner:"Risk Team",spoc:"",tech:"Python",blocker:"",eta:"",mc:"Yes",mc_reason:"Prop and allocation is risk-sensitive; macro output needs checker review before trading.",current_status:"Updated tracker sheet with additional columns received."},
  {project:"Generic Reco — Python Framework",category:"Automation",status:"Dev Complete",priority:"P3",rag:"G",owner:"Internal Team",spoc:"",tech:"Python",blocker:"",eta:"",mc:"No",mc_reason:"Internal utility framework; actual reco outputs have their own approval process.",current_status:"Generic reconciliation of any two files using Python framework."},
  {project:"Reco — LD vs CMA",category:"Automation",status:"Live",priority:"P1",rag:"G",owner:"Abhishek Bhagat",spoc:"",tech:"Python",blocker:"",eta:"",mc:"Yes",mc_reason:"LD vs CMA reconciliation feeds risk team decisions; exception reports need Risk sign-off.",current_status:"Reconciliation for LD vs CMA live. Validation API done in UAT."},
  {project:"ICS — Bank Channel Dealer Incentive",category:"Automation",status:"On Hold",priority:"",rag:"G",owner:"Mahek Tardeja",spoc:"",tech:"Python",blocker:"",eta:"",mc:"Yes",mc_reason:"Dealer incentive calculations impact payroll; outputs must be verified by HR.",current_status:"Dealer incentive calculations on monthly basis for bank channel."},
  {project:"ICS — Commodity Segment Brokerage",category:"Automation",status:"On Hold",priority:"",rag:"G",owner:"Mahek Tardeja",spoc:"",tech:"Python",blocker:"",eta:"",mc:"Yes",mc_reason:"Brokerage calculations affect client billing; must be reviewed by HR/Finance.",current_status:"ICS Commodity Segment Brokerage working."},
  {project:"ICS — Market Share Component",category:"Automation",status:"On Hold",priority:"",rag:"G",owner:"Team",spoc:"",tech:"",blocker:"",eta:"",mc:"Partial",mc_reason:"Market share data used for reporting; periodic review needed.",current_status:"ICS Market Share component working."},
  {project:"ICS — SIPIT & Stockcase",category:"Automation",status:"On Hold",priority:"",rag:"G",owner:"Team",spoc:"",tech:"Python",blocker:"",eta:"",mc:"Yes",mc_reason:"SIPIT and Stockcase outputs feed incentive calculations; must be validated.",current_status:"Estimates: 15 days."},
  {project:"ICS — Brokerage Component",category:"Automation",status:"On Hold",priority:"",rag:"G",owner:"Mahek Tardeja",spoc:"",tech:"Python",blocker:"",eta:"",mc:"Yes",mc_reason:"Brokerage calculations are financial; checker review before output is consumed.",current_status:"ICS Brokerage Component Working."},
  {project:"ICS — Daily Active Users Component",category:"Automation",status:"On Hold",priority:"",rag:"G",owner:"Mahek Tardeja",spoc:"",tech:"Python",blocker:"",eta:"",mc:"No",mc_reason:"DAU is a reporting metric; no direct financial or regulatory consequence.",current_status:"ICS Daily Active Users (DAU) component working."},
  {project:"ICS — MTF",category:"Automation",status:"On Hold",priority:"",rag:"G",owner:"Team",spoc:"",tech:"",blocker:"",eta:"",mc:"Partial",mc_reason:"MTF data requires periodic review given its risk implications.",current_status:"ICS MTF Working."},
  {project:"ICS — New Client Activation Component",category:"Automation",status:"On Hold",priority:"",rag:"G",owner:"Team",spoc:"",tech:"",blocker:"",eta:"",mc:"No",mc_reason:"New client activation tracking is informational; no financial action triggered.",current_status:"ICS New clients activation component working."},
  {project:"ICS — SLBM Brokerage Component",category:"Automation",status:"On Hold",priority:"",rag:"G",owner:"Mahek Tardeja",spoc:"",tech:"Python",blocker:"",eta:"",mc:"Yes",mc_reason:"SLBM brokerage is a financial calculation; outputs feed HR disbursements.",current_status:"ICS SLBM brokerage component."},
  {project:"Core Risk Template",category:"Automation",status:"Live",priority:"",rag:"G",owner:"Abhishek Bhagat",spoc:"",tech:"Python",blocker:"",eta:"",mc:"Yes",mc_reason:"Risk ledger dashboard feeds Risk team decisions; needs Risk team verification.",current_status:"Ledger dashboard created in Excel using BO_Repo data on request."},
  {project:"KWeb — BOSS Historical Reports",category:"Development",status:"Live",priority:"",rag:"G",owner:"Ops Team",spoc:"",tech:"SQL",blocker:"",eta:"",mc:"No",mc_reason:"Historical report replication for Excel download; read-only informational output.",current_status:"KWeb reports for BOSS historical data. Excel download replication live."},
  {project:"HR Chatbot",category:"Automation",status:"On Hold",priority:"",rag:"G",owner:"HR(Rajendra)",spoc:"",tech:"Copilot Studio",blocker:"",eta:"",mc:"No",mc_reason:"HR policy Q&A chatbot; no decision or transaction executed by the bot.",current_status:"HR policy chatbot using Microsoft CoPilot. Copilot licence required."},
  {project:"PDF Data Extraction — Margin Status",category:"Automation",status:"Requirement Gathering",priority:"",rag:"G",owner:"Abhishek Bhagat",spoc:"",tech:"Python, Power Automate",blocker:"",eta:"",mc:"Yes",mc_reason:"Margin status data is risk-sensitive; extracted data must be validated before use.",current_status:"Information to be extracted and saved in Excel using RPA tool for Risk Team."},
  {project:"Customer Communication Repository — SMS",category:"Development",status:"Live",priority:"",rag:"G",owner:"IT APPS (Iyer Satyanarayan)",spoc:"",tech:"SQL, Python",blocker:"",eta:"",mc:"No",mc_reason:"SMS repository is a read-only archive; no outbound communication triggered.",current_status:"Enterprise Customer Communication Repository for SMS, Email and WhatsApp live."},
  {project:"Dematrix SOH Reco",category:"Automation",status:"Live",priority:"",rag:"G",owner:"IT APPS (Iyer Satyanarayan)",spoc:"",tech:"SSIS, SQL",blocker:"",eta:"",mc:"Yes",mc_reason:"SOH reconciliation has regulatory implications; exception reports need IT APPS sign-off.",current_status:"Dematrix Holding file reco for KSec, KMBL and IBL live."},
  {project:"Employee Data Upload Automation — Disprz",category:"Automation",status:"Live",priority:"",rag:"G",owner:"Mahek Tardeja",spoc:"",tech:"Power Automate",blocker:"",eta:"",mc:"Partial",mc_reason:"Employee add/delete/modify is HR-sensitive; exceptions require HR team verification.",current_status:"Daily addition, deletion and modification of employee details in Disprz portal. Live."},
  {project:"Shortfall as per Segregation",category:"Automation",status:"Live",priority:"",rag:"G",owner:"Abhishek Bhagat",spoc:"",tech:"Python",blocker:"",eta:"",mc:"Yes",mc_reason:"Segregation shortfall reco has regulatory compliance consequences.",current_status:"Reconciliation for segregation shortfalls using LD GMR reports and regulatory data."},
  {project:"Pledge Extract Reco with Upload Modules",category:"Automation",status:"On Hold",priority:"",rag:"G",owner:"Abhishek Bhagat",spoc:"",tech:"Python",blocker:"",eta:"",mc:"Yes",mc_reason:"Pledge data upload to exchange is regulatory-critical; requires Risk team checker.",current_status:"UAT 20.11.25. In Development."},
  {project:"CSAT-NPS — Customer Feedback Classification",category:"Automation",status:"On Hold",priority:"",rag:"G",owner:"Naincy Raj",spoc:"",tech:"Power Automate",blocker:"",eta:"",mc:"No",mc_reason:"AI classification of feedback is an internal analytics task; no financial action triggered.",current_status:"Review and categorize client feedback. Chatbot for product team. On hold."},
  {project:"OPS — PnL PDF Data Extraction",category:"Automation",status:"Live",priority:"",rag:"G",owner:"Sandesh Dhuri",spoc:"",tech:"Python",blocker:"",eta:"",mc:"Yes",mc_reason:"PnL data extraction feeds financial reporting; OPS team must verify extracted data.",current_status:"Extracted data from PnL Statement PDFs as per requirement. UAT done."},
  {project:"Indemnity PDF Extraction",category:"Automation",status:"Live",priority:"",rag:"G",owner:"Sandesh Dhuri",spoc:"",tech:"Power Automate AI builder",blocker:"",eta:"",mc:"Yes",mc_reason:"Indemnity documents are legal; extracted data must be reviewed by Ops team.",current_status:"Read data from scanned PDFs and write table-formatted data into Excel. Live."},
  {project:"Haircut Data Download",category:"Automation",status:"Requirement Gathering",priority:"",rag:"G",owner:"Abhishek Bhagat",spoc:"",tech:"Power Automate",blocker:"",eta:"",mc:"Partial",mc_reason:"Haircut data is regulatory; should have periodic review but no per-run approval.",current_status:"Fetch stock and ETF haircut data from exchange website."},
  {project:"Editable PDF Form",category:"Automation",status:"Live",priority:"",rag:"G",owner:"Mahek Tardeja",spoc:"",tech:"Adobe pro",blocker:"",eta:"",mc:"No",mc_reason:"Form digitisation for HR; filled and submitted by end user, no decision automated.",current_status:"Editable PDF form for digital submission by HR team. Live."},
  {project:"LD EOD Process Automation",category:"Automation",status:"Requirement Gathering",priority:"",rag:"R",owner:"Kiran Amin",spoc:"",tech:"Power Automate",blocker:"Waiting for LD application setup and PowerAutomate License",eta:"",mc:"No",mc_reason:"EOD file download automation; no financial transaction or approval decision in the flow.",current_status:"Automation of manual EOD process. LD setup and PA licence pending."},
  {project:"Reco — LD vs BO_DP (Golden Gate)",category:"Automation",status:"Live",priority:"",rag:"G",owner:"IT APPS (Iyer Satyanarayan)",spoc:"",tech:"Python",blocker:"",eta:"",mc:"Yes",mc_reason:"Count reco between LD and BO systems; discrepancies require IT APPS review.",current_status:"Count reco between LD and BO live."},
  {project:"Global API Logger",category:"Development",status:"Live",priority:"",rag:"G",owner:"Prashant Patil",spoc:"",tech:"Python",blocker:"",eta:"",mc:"No",mc_reason:"Internal logging utility; no decision or approval workflow involved.",current_status:"Global API Logger live."},
  {project:"Risk EOD — API Segregation",category:"Automation",status:"Live",priority:"P1",rag:"G",owner:"Abhishek Bhagat",spoc:"",tech:"Power Automate",blocker:"",eta:"",mc:"No",mc_reason:"Separate API per file is a technical decomposition; no additional approval gate.",current_status:"Separate API created for each file download for Risk Team."},
  {project:"CSAT-NPS — Bot",category:"Automation",status:"On Hold",priority:"",rag:"G",owner:"Naincy Raj",spoc:"",tech:"Copilot Studio",blocker:"",eta:"",mc:"No",mc_reason:"Customer feedback bot; read-only Q&A, no financial or regulatory decision made.",current_status:"CSAT-NPS Bot on hold."},
  {project:"Statement Automation — Dev & Support",category:"Development",status:"In Progress",priority:"P1",rag:"A",owner:"Subramaniam Nambiar",spoc:"",tech:".Net, SQL",blocker:"",eta:"",mc:"Yes",mc_reason:"Client-facing statements are regulatory documents; must be reviewed before dispatch.",current_status:"Statement Automation Dev and Support in progress."},
  {project:"Server 86 — Python Library Standardization",category:"Standardization",status:"In Progress",priority:"P2",rag:"G",owner:"Internal Team",spoc:"",tech:"Python",blocker:"",eta:"",mc:"No",mc_reason:"Library standardization is an internal dev-ops activity; no external approval required.",current_status:"Python library standardization on server 86."},
  {project:"Global Config Setup",category:"Standardization",status:"In Progress",priority:"P1",rag:"G",owner:"Internal Team",spoc:"",tech:"",blocker:"",eta:"",mc:"No",mc_reason:"Internal config file setup; no approval gate needed.",current_status:"Global config setup in progress."},
  {project:"HO (OPS) — Reconciliation/Automation",category:"Automation",status:"Requirement Gathering",priority:"P2",rag:"R",owner:"Yogesh Parve",spoc:"",tech:"Python",blocker:"On hold from OPS side",eta:"",mc:"Yes",mc_reason:"DP and Trading profile reco has direct client impact; off-market transaction emails need OPS maker-checker.",current_status:"DP and Trading profile table-to-table reco of Dematrix and LD."},
  {project:"Server 86 — Backup & DR Plan",category:"Infrastructure",status:"Requirement Gathering",priority:"P3",rag:"G",owner:"Internal Team",spoc:"",tech:"",blocker:"",eta:"",mc:"Partial",mc_reason:"DR plan must be signed off by IT management before activation.",current_status:"Backup and DR plan for server 86."},
  {project:"Risk Files — Exchange Portal Download",category:"Automation",status:"Requirement Gathering",priority:"P2",rag:"G",owner:"Ashish Gharia",spoc:"",tech:"Power Automate",blocker:"",eta:"",mc:"No",mc_reason:"Exchange file download automation; files subsequently uploaded to LD with existing controls.",current_status:"Downloading files from exchange websites/portals."},
  {project:"GreekSoft Exe File Download",category:"Automation",status:"Requirement Gathering",priority:"P2",rag:"G",owner:"Kinjal Thakkar",spoc:"",tech:"Power Automate",blocker:"",eta:"",mc:"Partial",mc_reason:"Input file for prop and allocation automation; download step should be verified periodically.",current_status:"Download files from GreekSoft exe application for prop and allocation."},
  {project:"SBO — Emailer Automation",category:"Automation",status:"In Progress",priority:"P2",rag:"G",owner:"Vidyadar Bangera",spoc:"",tech:"Python",blocker:"",eta:"",mc:"Yes",mc_reason:"Bulk emailer sent to clients/stakeholders; content and recipient list must be reviewed.",current_status:"45 emailers to be sent by automation. In progress."},
  {project:"HR Policy Chatbot — AWS",category:"Automation",status:"Requirement Gathering",priority:"P2",rag:"G",owner:"Kamlesh Lakum",spoc:"",tech:"Python, AWS",blocker:"",eta:"",mc:"No",mc_reason:"HR policy Q&A chatbot; informational only, no decisions or transactions triggered.",current_status:"HR Policy Chatbot on AWS. Requirement gathering."}
];

module.exports = async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  if (req.method === 'OPTIONS') return res.status(200).end();

  const token = req.headers['x-seed-token'] || req.query.token;
  if (token !== process.env.SEED_SECRET)
    return res.status(401).json({ error: 'Unauthorized. Pass x-seed-token header.' });

  await supabase.from('projects').delete().neq('id', 0);
  const { data, error } = await supabase.from('projects').insert(PROJECTS).select();
  if (error) return res.status(500).json({ error: error.message });
  return res.status(200).json({ message: `Seeded ${data.length} projects`, count: data.length });
};
